"""All baseline parameter values in one place."""

SEED: int = 42
PERIODS: int = 80

N_HOUSEHOLDS: int = 100
N_FIRMS: int = 8
N_BANKS: int = 2

INITIAL_HOUSEHOLD_DEPOSITS_MIN: float = 4.0
INITIAL_HOUSEHOLD_DEPOSITS_MAX: float = 12.0
INITIAL_FIRM_DEPOSITS: float = 5.0

PROPENSITY_TO_CONSUME_MIN: float = 0.55
PROPENSITY_TO_CONSUME_MAX: float = 0.85

PRODUCTIVITY_MIN: float = 0.85
PRODUCTIVITY_MAX: float = 1.20
INITIAL_PRICE_MIN: float = 1.15
INITIAL_PRICE_MAX: float = 1.45
WAGE: float = 1.0

TAX_RATE: float = 0.15
UNEMPLOYMENT_BENEFIT: float = 0.55
INTEREST_RATE: float = 0.01
DEBT_REPAYMENT_RATE: float = 0.05

EXPECTATION_ADJUSTMENT: float = 0.40
PRODUCTION_BUFFER: float = 0.10
PRICE_ADJUSTMENT: float = 0.02
INVENTORY_TARGET_SHARE: float = 0.50
MINIMUM_MARKUP: float = 0.05

